import numpy as np
a= [1,2,3,4,5]
na = np.array(a)
print(na)

nb = np.array([[1,2,3],[4,5,6]])
nb[1] # nb 2차원 배열에서 2행의 모든걸 다 뽑아 낸다

nb[1,2]

- 파이썬의 기본형 int는 Numpy에서 np.int64와 동일

- Python의 float는 Numpy에서는 np.float64와 동일

nc = np.array([1.2,2.3,3.4])
nc[2]

nb.sum() # 행렬 모든 요소를 합

nb.sum(axis = 0) # 열 기준으로 합산

nb.sum(axis = 1) # 행 기준으로 합산

# 랜덤 데이터 생성
np.random.rand(5)

np.random.randint(1,10,5) # 1부터 10까지를 5개 숫자로 임의로 나눠라

# 정규화
nd = np.array([10,20,30])

normalized = (nd- nd.mean())/ nd.std()
normalized

# 점수 데이터 합격자만 추출
 
scores = np.array([50,80,90,60,30])
scores[scores >= 60]

- 정리
    - list: 파이썬 for문 
    - Numpy: C언어 기반 처리
    - 넘파이가 리스트보다 훨씬 빠르다

scores.mean() # score의 평균값

# Pandas 설치
!pip install pandas

!pip install pandas

!pip list

### 판다스 기초
- 핵심 구조
    - DataFrame(데이터프레임): 기준, 2차원 배열
    - Series(시리즈): 최소 원소,1차원 배열

In [2]:
# 판다스 라이브러리 모드
import pandas as pd

In [3]:
#시리즈
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [ ]:
# 데이터 프레임
# 딕셔너리 타임
data = {
    "name":['John','Anna','Mike'],
    'score':[90,100,36]
    }
data

{'name': ['John', 'ANnna', 'Mike'], 'score': [90, 100, 36]}

In [ ]:
# DataFrame
df= pd.DataFrame(data)
df

    name  score
0   John     90
1  ANnna    100
2   Mike     36

In [38]:
# CSV 읽기
df = pd.read_csv('./도서정보.csv')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [ ]:
# CSV 읽기
df = pd.read_csv('./도서정보.csv')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [9]:
# 엑셀 파일 읽기
df = pd.read_excel('./sample.xlsx')
df

    이름   국어   영어   수학
0  홍길동   95   98   93
1  애슐리  100  100  100

- 엑셀을 읽을려면 openpyxl 모듈이 추가로 필요

```bash
!pip install openpyxl
```

In [ ]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### 데이터 확인 및 편집
- 데이터 분석시 핵심 기술

In [11]:
df = pd.read_csv('./도서정보.csv')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [ ]:
# 데이터 확인
df.head() # 기본 상위 5개만 출력

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실

In [14]:
df.head(3) # 숫자를 넣어주면 갯수 확인 가능

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실

In [ ]:
df.tail() # tail은 하위 5개만 출력

,번호,서명,저자,발행자,발행년,청구기호,자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [16]:
# 타입정보 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      10 non-null     int64
 1   서명      10 non-null     str
 2   저자      10 non-null     str
 3   발행자     10 non-null     str
 4   발행년     10 non-null     str
 5   청구기호    10 non-null     str
 6   자료실     10 non-null     str
dtypes: int64(1), str(6)
memory usage: 692.0 bytes

- NULL 값은 통계에서 치명적인 데이터
- NULL 데이터가 없도록 만들어 주는것이 데이터 분석전 핵심 작업

In [17]:
df.describe()

             번호
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

In [25]:
# 컬럼 선택
df[['서명']].info() ## 이렇게 서명만 떼서 오면 series이다.

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   서명      10 non-null     str
dtypes: str(1)
memory usage: 212.0 bytes

In [ ]:
#새로 데이터프레임 읽기
df = pd.read_excel('./sample.xlsx')
df

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

In [29]:
# 국어점수가 60점 이상만 필터링
df['국어'] > 60

0     True
1     True
2     True
3    False
Name: 국어, dtype: bool

In [30]:
df[df['국어'] > 60]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78

In [32]:
#영어 점수가 50 이상만 필터링

df['영어'] >50

0     True
1     True
2    False
3    False
Name: 영어, dtype: bool

In [33]:
df[df['영어'] >50]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   국어      4 non-null      int64
 2   영어      3 non-null      float64
 3   수학      4 non-null      int64
dtypes: float64(1), int64(2), str(1)
memory usage: 260.0 bytes

In [36]:
df.describe()

               국어          영어          수학
count    4.000000    3.000000    4.000000
mean    83.750000   82.666667   92.750000
std     22.867371   28.307832   10.372239
min     50.000000   50.000000   78.000000
25%     80.000000   74.000000   89.250000
50%     92.500000   98.000000   96.500000
75%     96.250000   99.000000  100.000000
max    100.000000  100.000000  100.000000

#### 결측치(중요)
- 실제 data 수집 과정에서 누락 되거나 측정 되지 않는 빈 값
- 데이터 분석에서는 결측치를 처리 하는일이 가장 중요

In [44]:
df['수학_1'] = df['수학'] - 5
df

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90    NaN   78    73
3  김예성   50   50.0  100    95

In [45]:
df.sort_values('수학_1')

    이름   국어     영어   수학  수학_1
2  성명건   90    NaN   78    73
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95

In [47]:
df.sort_values('수학_1',ascending = False)

    이름   국어     영어   수학  수학_1
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95
0  홍길동   95   98.0   93    88
2  성명건   90    NaN   78    73

In [ ]:
df1 = df.dropna() # 결측치가 있는 데이터행을 아예 없앤다.
df1

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95

In [ ]:
df2 = df.fillna(45) #결측치가 있는 데이터에 값은 넣는다.
df2

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90   45.0   78    73
3  김예성   50   50.0  100    95

In [51]:
# 그룹화(GroupBy)
df.groupby('수학').count()

     이름  국어  영어  수학_1
수학
78    1   1   0     1
93    1   1   1     1
100   2   2   2     2

In [55]:
df[['국어','영어','수학']].fillna(45).groupby('수학').mean()
df

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90    NaN   78    73
3  김예성   50   50.0  100    95

In [56]:
data = {
'name': ['유고','요미','철수','예성'],
'score': [80,95,60,70]
}

df = pd.DataFrame(data)
df

  name  score
0   유고     80
1   요미     95
2   철수     60
3   예성     70

In [57]:
df.to_csv('./scores.csv',encoding = 'utf-8')

In [ ]:
df[df['score'] >= 70]

  name  score
0   유고     80
1   요미     95
3   예성     70

In [61]:
df['score'].mean()

np.float64(76.25)

In [68]:
#합격 여부
#리스트 컴프리헨션으로 새 컬럼 생성
['PASS'if s>=70 else 'FAIL' for s in df['score']]

['PASS', 'PASS', 'FAIL', 'PASS']

In [70]:
df['result'] = ['PASS'if s>=70 else 'FAIL' for s in df['score']]
df

  name  score result
0   유고     80   PASS
1   요미     95   PASS
2   철수     60   FAIL
3   예성     70   PASS